"""Added images to movies"

Revision ID: 1088d9769584
Revises: f61ffdb9ce67
Create Date: 2023-04-18 11:17:01.996921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1088d9769584'
down_revision = 'f61ffdb9ce67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
