"""Changed rating to review

Revision ID: 228c15cf953d
Revises: 073424e76009
Create Date: 2023-04-17 14:53:45.885500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228c15cf953d'
down_revision = '073424e76009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Integer(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###
