"""Removed reviews

Revision ID: 789c0393ddd9
Revises: a98cc9815d97
Create Date: 2023-04-19 15:06:21.928085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789c0393ddd9'
down_revision = 'a98cc9815d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('movie_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_reviews_customer_id_customers'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='fk_reviews_movie_id_movies'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
